### ISSUE TITLE
Undefined log_finite

### ISSUE THREAD

**Issue by iamholger** [JohannesBuchner/cuba#1]
Hi Johannes,

I build the shared libcuba.so with according to your instructions but when 
trying to import pycuba in python I get this error:

`OSError: /usr/local/lib/libcuba.so: undefined symbol: _ZGVbN2v___log_finite`

nm -CD on /usr/local/lib/libcuba.so indeed flags up a few undefined bits:
                 U _ZGVbN2v___log_finite
                 U __exp_finite
                 U __pow_finite
                 U __powl_finite

Do you happen to know which library provides these symbols?

Thanks,
Holger

**Comment by iamholger** [comment]
Hi Johannes,

just to report I fixed it by adding libmath explicitly to the gcc command in makesharedlibs.sh as such:

./configure &&  sed -i "s|-o libcuba.so|-lm -o libcuba.so|g" makesharedlib.sh &&  ./makesharedlib.sh

Thanks,
Holger

**Comment by JohannesBuchner** [comment]
This should finally be fixed in commit 595ce84e2d893381fe4e15e204ffc7da57c3c91c

**Comment by Astrokiwi** [comment]
I installed using the instructions [here](http://johannesbuchner.github.io/PyMultiNest/install.html) and got the same issue. Git log shows that this is indeed the version that you modified on Feb 27. Using the script suggested by @iamholger resolved the problem.

**Comment by JohannesBuchner** [comment]
So -lm has to go after $FILES, otherwise it does not work?

**Comment by Astrokiwi** [comment]
Maybe! I just copied the line above, I'm not the greatest at makefile-fu

**Comment by lbarosi** [comment]
I am afraid this just be still open. I installed today from github, Multinest, Cuba and PyMultinest into a customized docker cosmobox(from cambant). Everything went fine, except for **cuba**. 

Using the fix above from @ianholger did the job.

**Comment by JohannesBuchner** [comment]
@lbarosi: Could you test whether modifying the Makefile so that -lm goes after $FILES works?

**Comment by lbarosi** [comment]
@JohannesBuchner indeed it works. 
````
gcc -shared -Wall  $FILES -lm -o libcuba.so
````
Also to mention, in documentation an update of library Atlas for DEB installations. (http://johannesbuchner.github.io/PyMultiNest/install.html#prerequisites-for-building-the-libraries), 
````
# sudo apt install libatlas{3-base,-dev}
sudo apt install libatlas{3-base,-base-dev} 
````

**Comment by scarlehoff** [comment]
Just wanted to add that I find the same error (and fixed it with the same solution)

**Comment by JohannesBuchner** [comment]
OK, I ran into this myself and fixed it, but hadn't pushed yet. Please try with the latest commit.
